.MODEL SMALL
.DATA
    POSIT DB 10,13,"POSITIVO!$"
    NEGAT DB 10,13,"NEGATIVO!$"
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV AH,01
    INT 21H
    AND AL,0FH
    MOV AH,09
    TEST AL,80H
    JNZ NEGATIVO
    LEA DX,POSIT
NEGATIVO: LEA DX,NEGAT
    INT 21H
    MOV AH,4CH
    INT 21H
MAIN ENDP
END MAIN